# Generated by Django 5.2.7 on 2025-10-07 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskviewer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskviewer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskviewer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskoutput',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Task Output', 'verbose_name_plural': 'Task Outputs'},
        ),
        migrations.AlterModelOptions(
            name='taskoutputfield',
            options={'ordering': ['id'], 'verbose_name': 'Task Output Field', 'verbose_name_plural': 'Task Output Fields'},
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to complete this task', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='Users who can only view this task', related_name='viewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this task is associated with', related_name='tasks', to='organizations.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(help_text='Organization this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='taskoutputfield',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Maximum value for number fields', null=True),
        ),
        migrations.AlterField(
            model_name='taskoutputfield',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Minimum value for number fields', null=True),
        ),
        migrations.AlterField(
            model_name='taskoutputfield',
            name='options',
            field=models.TextField(blank=True, help_text='Comma separated options for radio/checkbox fields', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='taskoutput',
            unique_together={('output_field', 'user')},
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
        migrations.DeleteModel(
            name='TaskViewer',
        ),
    ]
