# Generated by Django 5.2.7 on 2025-10-07 21:14

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskviewer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoutput',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='taskoutput',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename before sanitization', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskoutput',
            name='value_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tasks.models.task_output_upload_path),
        ),
    ]
